---
- name: ssh start service
  hosts: all
  tasks:
    - name: STOP a service with systemd
      systemd:
        name: cups
        state: stopped
        - name: start a service with systemd
        systemd:
        name: httpd
        state: started
