name: Stop service httpd, if started
  ansible.builtin.service:
    name: httpd
    state: stopped
    
    name: Stop service firewalld, if started
  ansible.builtin.service:
    name: firewalld
    state: stopped
    
    name: Stop service cups, if started
  ansible.builtin.service:
    name: cups
    state: stopped
    
    name: Stop service nfs-server, if started
  ansible.builtin.service:
    name: nfs-server
    state: stopped
   
   name: Start service sshd, if not started
  ansible.builtin.service:
    name: sshd
    state: started
    
    name: Start service chrony, if not started
  ansible.builtin.service:
    name: chrony
    state: started
